<?php
/**
 * @file
 * Code for the GSB Feature Person Display feature.
 */

include_once 'gsb_feature_people_fpp.features.inc';

function gsb_feature_people_fpp_entity_info_alter(&$entity_info) {

  $entity_info['fieldable_panels_pane']['bundles']['people'] = array(
    'label' => t('People'),
    'pane category' => t('GSB panes'),
    'pane top level' => TRUE, // set to true to make this show as a top level icon
    'pane icon' => drupal_get_path('module', 'panopoly_widgets') . '/images/icon_text.png',
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      // Note that this has all _ replaced with - from the bundle name.
      'real path' => 'admin/structure/fieldable-panels-panes/manage/people',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );

}

/**
 * Implements hook_fieldable_panels_pane_view_alter().
 */
function gsb_feature_people_fpp_fieldable_panels_pane_view_alter(&$build, $entity_type) {
  $wrapper = entity_metadata_wrapper($entity_type, $build["#$entity_type"]);
  if ($wrapper->getBundle() != 'people') {
    return;
  }

  // Hide the view that wasn't chosen in the UI.
  $show = $wrapper->field_persons_display_style->value();
  foreach (array('people_fpp_view_list', 'people_fpp_view_grid') as $view) {
    $build[$view]['#access'] = ($view == $show);
  }
}
