<?php
/**
 * @file
 * Code for the GSB Feature Person feature.
 */

include_once 'gsb_feature_person.features.inc';

function gsb_feature_person_entity_info_alter(&$entity_info) {
  $entity_info['fieldable_panels_pane']['bundles']['gsb_feature_person'] = array(
    'label' => t('Person'),
    'pane category' => t('GSB Person'),
    'pane top level' => TRUE, // set to true to make this show as a top level icon
    'pane icon' => drupal_get_path('module', 'panopoly_widgets') . '/images/icon_text.png',
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      // Note that this has all _ replaced with - from the bundle name.
      'real path' => 'admin/structure/fieldable-panels-panes/manage/gsb-feature-person',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
}

function gsb_feature_person_preprocess_panels_pane(&$vars) {
  $test = 'test';
  //if ($vars['pane']->type == 'node_title') {
    //$vars['template_files'][] = 'panels-pane-node-title';
  //}
}

function gsb_feature_person_preprocess_fieldable_panels_pane(&$vars) {

  $view_name = "test_view";
  $display_id = "page";

  if (isset($vars['field_person_node_ref'])) {

    if ($view = views_get_view($view_name)) {

      $node_ids = array();

      foreach ($vars['field_person_node_ref'] as $key => $value) {
        $node_ids[] = $value['entity']->nid;
      }

      $ids = implode("+", $node_ids);
      $node_ids = array($ids);

      $view->set_display($display_id);
      $vars['fields'] = $view->preview($display_id, $node_ids);

    }

  }

}

function gsb_feature_person_views_pre_render(&$view) {

  if ('test_view' == $view->name) {

    $args = explode("+", $view->args[0]);
    
    $result_ids = array();

    foreach($view->result as $key => $value) {
      $result_ids[] = $value->nid;
    }

    $ordered_results = array();
    foreach($args as $key => $value) {
      $index = array_search($args[0], $result_ids);
      $ordered_results[] = $view->result[$index];
    }

    $view->result = $ordered_results;

    $test = "test";

    //$view->result = array_reverse($view->result);
  }
  
}
