<?php
/**
 * @file
 * Code for the GSB Feature Person feature.
 */

include_once 'gsb_feature_person.features.inc';

function gsb_feature_person_entity_info_alter(&$entity_info) {
  $entity_info['fieldable_panels_pane']['bundles']['gsb_feature_person'] = array(
    'label' => t('Person'),
    'pane category' => t('GSB Person'),
    'pane top level' => TRUE, // set to true to make this show as a top level icon
    'pane icon' => drupal_get_path('module', 'panopoly_widgets') . '/images/icon_text.png',
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      // Note that this has all _ replaced with - from the bundle name.
      'real path' => 'admin/structure/fieldable-panels-panes/manage/gsb-feature-person',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
}
